---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: book-install
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/bookinfo/install
  prune: false
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: bookinfo
  validation: client

