---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tsbmp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./deploy/tsbcp
      sourceRef:
        kind: GitRepository
        name: instavote
  interval: 10m0s
  targetNamespace: tsb

