---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: voteapp
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: instavote
    namespace: instavote
  interval: 1m0s
  path: ./deploy/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s

